# Setup
title:               Jacek Grela
tagline:             'physics/math/ML/data'
description:         'resume of an applied theoretical physicist'
url:                 'https://grelade.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jacek Grela
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
