title: "On the crossroads"
subtitle: "Jacek Grela"
author: "Jacek Grela"
description: "Jacek Grela"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
mathjax: true

use_google_analytics: true
google_analytics_id: "G-QBBQCQ452M"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html",title: "CV"}
  - {file: "blog.html",title: "Blog"}
  - {file: "projects.md",title: "Projects"}
  # - {file: "archive.html",title: "Archive"}
  # - {file: "README.md"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Twitter X, icon: twitter, url: "https://twitter.com/JacekGrela2501"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/jacek-grela-278275113"}
  - {title: Medium, icon: medium, url: "https://medium.com/@jacekgrela"}
  - {title: Github, icon: github, url: "https://github.com/grelade"}
  - {title: Quora, icon: quora, url: "https://www.quora.com/profile/Jacek-Grela"}
  - {title: Google Scholar, icon: google ,url: "https://scholar.google.com/citations?user=jp8Z9WEAAAAJ&hl=pl&oi=ao"}
  - {title: Mail, icon: envelope, url: "mailto:jacekgrela@gmail.com"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 # - jekyll-figure

exclude: [dump]
